config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  # root to: "pages#home"
  root to: "players#index"
  resources :players, except: :index do
    resources :bookings, only: %i[create destroy]
  end

  get 'dashboard', to: 'pages#dashboard', as: :dashboard

  patch 'bookings/:id/accept', to: 'bookings#accept', as: :accept
  patch 'bookings/:id/decline', to: 'bookings#decline', as: :decline

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

# formulaire booking sur la show de players
# controller pages def dashboard -> ensuite view

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :player
  belongs_to :user

  # validates_date :rent_start, on_or_before: lambda { Date.current }
  # validates_date :rent_end, on_or_before: lambda { Date.current }
  # validates :rent_status, presence: true, inclusion: { in: ["Accept", "Decline"] }
  validates :user_id, :player_id, presence: true
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo


  validates :name, presence: true
  validates :club, presence: true

  scope :filter_by_status, -> (status) { where status: status }
  scope :filter_by_location, -> (location_id) { where location_id: location_id }
  scope :filter_by_starts_with, -> (name) { where("name like ?", "#{name}%")}
  # validates :user_id, presence: true, through: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :bookings
  has_many :players

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @booking = Booking.new
  end

  def create
    @player = Player.find(params[:player_id])
    @booking = Booking.new(booking_params)
    @booking.player = @player
    @booking.user = current_user
    if @booking.save
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.status = "Accepted"
    @booking.save
    redirect_to dashboard_path
  end


  def decline
    @booking = Booking.find(params[:id])
    @booking.status = "Declined"
    @booking.save
    redirect_to dashboard_path
  end


  def destroy
    #if status decline booking.destroy status pending en db parce que pas encore accepté
  end

  private

  def booking_params
    params.require(:booking).permit(:rent_start, :rent_ending)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
    @my_players = current_user.players
    @my_bookings = current_user.bookings
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
skip_before_action :authenticate_user!, only: :index

# before_action :set_player, only: [:show]
#skip before action only [show index]

def index
  @recent_players = Player.last(3)

  if params[:query].present?
    sql_query = <<~SQL
      players.name ILIKE :query
    SQL
    @players = Player.where(sql_query, query: "%#{params[:query]}%")
  else
    @players = Player.all
  end

end


  def show
    @player = Player.find(params[:id])
    @booking = Booking.new
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.create(player_params)
    @player.user = current_user
    # player associé au user
    if @player.save
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player.update(player_params)
    redirect_to player_path(@player)
  end

  def destroy
    @player.destroy
    redirect_to player_path, status: :see_other
  end


  private

  def set_player
    @player = Player.find(params[:id])
  end

  def player_params
    params.require(:player).permit(:name, :club, :position, :rating, :age, :description, :price, :strong_foot)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Footbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
     <%= render "shared/footer" %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <h1>Mon profil</h1>
  <p>Bienvenue <%= current_user.first_name %></p>

  <div class="btn-green-flat">
<%= link_to "Create a player", new_player_path %>
  </div>

  <%#--------------------- Recruiting -------------------------------------------------------%>

  <h2>Players I recruited</h2>

  <div class="cards-dash">
    <% @my_bookings.each do |booking| %>
      <div class="card-product my-2">
            <% if booking.player.player_photo %>
            <%= image_tag player.player_photo%>
              <% else %>
            <img src="https://tbtech.co/wp-content/uploads/2021/03/Boris-Paillard-200ppi-scaled.jpg" alt="">
          <% end %>
        <div class="card-product-infos">
          <h2><%= booking.player.name  %></h2>
          <p>Product description with <strong>relevant info</strong> only.</p>
          <p>From: <%= booking.rent_start %> to <%= booking.rent_ending %> </p>
          <p>Status: <%= booking.status %> </p>
        </div>
      </div>
    <% end %>
  </div>
  <%#--------------------- Recruiting -------------------------------------------------------%>
  <%#--------------------- Created players -------------------------------------------------------%>
<hr class="my-5">

  <h2>My players</h2>


  <div class="my-player-card">


    <div class="card-info-dash">
      <% @my_players.each do |player| %>


      <div class="card-product my-2">
          <% if player.player_photo %>
            <%= image_tag player.player_photo%>
              <% else %>
            <img src="https://tbtech.co/wp-content/uploads/2021/03/Boris-Paillard-200ppi-scaled.jpg" alt="">
          <% end %>
        <div class="card-product-infos">
          <h2><%= player.name  %></h2>
          <p>Description:<%= player.description %> || Age: <%= player.age %> || Rating: <%= player.rating %></p>
          <p>Strong Foot: <%= player.strong_foot %> || Club: <%= player.club %> || </p>
          <h6>Price/day: <%= player.price %></h6>
        </div>
      </div>


        <div class="my-player-bookings ">
          <%player.bookings.each do |booking| %>
            <div class="my-player-booked border">
            <p>Booked By: <%= booking.user.email %></p>
              <p><%= booking.status %></p>
              <%= link_to "Accept", accept_path(booking), data: {turbo_method: :patch}, class:"btn btn-green-tiny" %>
              <%= link_to "Decline", decline_path(booking), data: {turbo_method: :patch}, class:"btn btn-grey-stroke"%>
              </div>
            <% end %>
          </div>
      </div>
    </div>
  <% end %>
  </div>

app/views/players/index.html.erb
<%#--------------------- Banner -------------------------------------------------------%>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path "banner_image.jpg"  %>);">
  <div class="container">
    <div class="text">
        <h1 class="mb-5">Top rating of the day</h1>
        <h4 class="mb-5">We celebrate Football at its finest.</h4>

        <%= form_with url: root_path, method: :get, class: "searchbar" do %>
          <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Search a player by name"%>
          <%= submit_tag "Search", class: "btn btn-success", style: "width: 200px"%>

        <% end %>
        <div class="btn-green-flat">
          <%= link_to "See all players", '#all-players', class: "btn-green-flat", class: "text-btn-green"%>
        </div>
    </div>
  </div>
</div>







<%#--------------------- Banner -------------------------------------------------------%>

<div class="container-body">
  <%#--------------------- Add 3 latest players -------------------------------------------------------%>

  <div class="title">
    <h2>Freshly added players</h2>
  </div>



  <div class="cards">


    <% @recent_players.each do |player| %>
        <div class="card-player">
          <% if player.player_photo %>
            <%= image_tag player.player_photo, class: 'image-player' %>
              <% else %>
            <img class="image-player" src="https://tbtech.co/wp-content/uploads/2021/03/Boris-Paillard-200ppi-scaled.jpg" alt="">
          <% end %>


          <div class="card-player-info">
            <div>
              <h2><%= player.name %></h2>
              <p><%= player.description %></p>
            </div>

            <div class="card-player-price">
              <h3>Prix:<%= player.price %>€</h3>
              <h3>Rating:<%= player.rating %>/100</h3>
            </div>
          <%=link_to "Rent", player_path(player), class: 'btn btn-outline-secondary p-2 flex-grow-0' %>
          </div>

        </div>
    <% end %>
  </div>


<hr>
  <%#--------------------- Add 3 latest players -------------------------------------------------------%>
  <%#--------------------- Filters -------------------------------------------------------%>

  <div class="title" id='all-players'>
    <h2>All players</h2>
    <p>Search by</p>
  </div>

  <div id="myBtnContainer">
    <button class="btn active" onclick="filterSelection('all')"> Show all</button>
    <button class="btn" onclick="filterSelection('age')"> Age</button>
    <button class="btn" onclick="filterSelection('rating')"> Rating</button>
    <button class="btn" onclick="filterSelection('strong foot')"> Strong foot</button>
    <button class="btn" onclick="filterSelection('position')"> Position</button>
    <button class="btn" onclick="filterSelection('club')"> Club</button>
  </div>

  <%#--------------------- Filters -------------------------------------------------------%>

  <%# ------------------------ cards ------------------------------------------------------------------%>



  <div class="cards">


    <% @players.each do |player| %>
        <div class="card-player">
          <% if player.player_photo %>
            <%= image_tag player.player_photo, class: 'image-player' %>
              <% else %>
            <img class="image-player" src="https://tbtech.co/wp-content/uploads/2021/03/Boris-Paillard-200ppi-scaled.jpg" alt="">
          <% end %>


          <div class="card-player-info">
            <div>
              <h2><%= player.name %></h2>
              <p><%= player.description %></p>
            </div>

            <div class="card-player-price">
              <h3>Prix:<%= player.price %>€</h3>
              <h3>Rating:<%= player.rating %>/100</h3>
            </div>
          <%=link_to "Rent", player_path(player), class: 'btn btn-outline-secondary p-2 flex-grow-0' %>
          </div>

        </div>
    <% end %>
  </div>

  <%# ------------------------ cards ------------------------------------------------------------------%>

</div>

app/views/players/new.html.erb
  <h1 class="titlez border shadow-effect"> Add a new player </h1>


<div class="w-50 mt-5" style="margin: 0 auto">
<%= simple_form_for(@player) do |f| %>

  <%= f.input :club, input_html: { class: 'shadow-effect' } %>
  <%= f.input :position, input_html: { class: 'shadow-effect' }%>
  <%= f.input :name, input_html: { class: 'shadow-effect' } %>
  <%= f.input :age, input_html: { class: 'shadow-effect' } %>
  <%= f.input :rating, input_html: { class: 'shadow-effect' } %>
  <%= f.input :strong_foot, input_html: { class: 'shadow-effect' } %>
  <%= f.input :price, input_html: { class: 'shadow-effect' } %>
  <%= f.input :description, input_html: { class: 'shadow-effect' } %>

  <%= f.submit 'Add your new player !', class: "sub" %>
<% end %>
</div>
  <%#= f.input, :photo,  as: :file %>

  <%#= f.input :player_photo, as: :string, input_html: { data: { flatpickr_target: "playerPhoto" } }  %>

app/views/players/show.html.erb
  <br>
  <br>
  <br>
  <div class="container">
  <h1>Player details</h1>
<div class = "container-fluid-show">


  <div class = "cardz col-4">
          <div class="cardz-player border">
           <% if @player.player_photo %>
            <%= image_tag @player.player_photo%>
              <% else %>
            <img src="https://tbtech.co/wp-content/uploads/2021/03/Boris-Paillard-200ppi-scaled.jpg" alt="">
          <% end %>
          </div>
          <div class="cardz-info xl-6">
            <div>
              <h2><%= @player.name %></h2>
            </div>
            <h2 class="cardsz-price"></h2>
            <h3><%= @player.rating %></h3>
          </div>
        </div>
    <div class="form-rent col-8">
        <%= simple_form_for [@player, @booking], data: { controller: 'flatpickr' } do |f| %>
          <%= f.input :rent_start, as: :string, input_html: { data: { flatpickr_target: "rentStart" }, class: 'shadow-effect' } %>
          <%= f.input :rent_ending, as: :string, input_html: { data: { flatpickr_target: "rentEnding" }, class: 'shadow-effect' } %>
          <%= f.submit 'Recruit your player for this period of time', class: 'btn btn-success shadow-effect' %>
      <% end %>
    </div>

</div>
</div>


<img class="football-field" src="https://images.unsplash.com/photo-1556056504-5c7696c4c28d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3257&q=80" alt="">

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/fbnbwagon/"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://static.vecteezy.com/system/resources/thumbnails/010/851/433/small/soccer-ball-illustration-png.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>

          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <% end %>
      </ul>
    </div>
  </div>
</div>